// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb1geo0e_ChMtF6nGNb3oU_YuVJr7KdJA',
    appId: '1:167372085731:web:1ceefa5d999d036e00e8d6',
    messagingSenderId: '167372085731',
    projectId: 'todo-project-pemmob',
    authDomain: 'todo-project-pemmob.firebaseapp.com',
    storageBucket: 'todo-project-pemmob.appspot.com',
    measurementId: 'G-5S1QHG4ZCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_u-ByTYCN1tJGZG78eVIfnwrL5g5swl8',
    appId: '1:167372085731:android:c6913fdfa7a9bfe100e8d6',
    messagingSenderId: '167372085731',
    projectId: 'todo-project-pemmob',
    storageBucket: 'todo-project-pemmob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-1V9HIAP7vLE5Eu2lKteTCWc-eIppEk8',
    appId: '1:167372085731:ios:b63c2310726c58ae00e8d6',
    messagingSenderId: '167372085731',
    projectId: 'todo-project-pemmob',
    storageBucket: 'todo-project-pemmob.appspot.com',
    iosBundleId: 'com.horizon.todoRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-1V9HIAP7vLE5Eu2lKteTCWc-eIppEk8',
    appId: '1:167372085731:ios:db2154f6c29cfa4d00e8d6',
    messagingSenderId: '167372085731',
    projectId: 'todo-project-pemmob',
    storageBucket: 'todo-project-pemmob.appspot.com',
    iosBundleId: 'com.horizon.todoRiverpod.RunnerTests',
  );
}
